"""empty message

Revision ID: 02001be7c937
Revises: 85293915804d
Create Date: 2019-09-26 14:35:59.204049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02001be7c937'
down_revision = '85293915804d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ride_category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ride_category')
    # ### end Alembic commands ###
