"""empty message

Revision ID: 0c90745a6433
Revises: 0d84207e1993
Create Date: 2019-09-17 20:34:20.589851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c90745a6433'
down_revision = '0d84207e1993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklist_tokens', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('blacklist_tokens', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('blacklist_tokens', 'updated_at')
    op.drop_column('blacklist_tokens', 'created_at')
    # ### end Alembic commands ###
