"""empty message

Revision ID: 47bc2e770d25
Revises: 0c90745a6433
Create Date: 2019-09-26 12:04:58.807053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47bc2e770d25'
down_revision = '0c90745a6433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number_plate', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'number_plate')
    # ### end Alembic commands ###
