"""empty message

Revision ID: 508f659b41ad
Revises: a62b9a0d1dec
Create Date: 2019-10-04 13:27:47.411489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508f659b41ad'
down_revision = 'a62b9a0d1dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address', sa.String(length=250), nullable=True))
    op.add_column('orders', sa.Column('distance', sa.BigInteger(), nullable=True))
    op.add_column('orders', sa.Column('pickup_address', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pickup_address')
    op.drop_column('orders', 'distance')
    op.drop_column('orders', 'delivery_address')
    # ### end Alembic commands ###
