"""empty message

Revision ID: 519f38bcbc25
Revises: 3dbbb2e65461
Create Date: 2019-10-04 11:18:37.693142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519f38bcbc25'
down_revision = '3dbbb2e65461'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_status')
    # ### end Alembic commands ###
