"""empty message

Revision ID: 793004df887f
Revises: 8030eaf3d454
Create Date: 2019-10-06 20:25:58.395069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793004df887f'
down_revision = '8030eaf3d454'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customer_id')
    # ### end Alembic commands ###
