"""empty message

Revision ID: 85293915804d
Revises: 47bc2e770d25
Create Date: 2019-09-26 13:22:01.513485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85293915804d'
down_revision = '47bc2e770d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('device_id', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'device_id')
    # ### end Alembic commands ###
