"""empty message

Revision ID: a62b9a0d1dec
Revises: 519f38bcbc25
Create Date: 2019-10-04 11:44:28.159739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a62b9a0d1dec'
down_revision = '519f38bcbc25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('delivery_lng', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('pickup_lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('pickup_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'pickup_lng')
    op.drop_column('orders', 'pickup_lat')
    op.drop_column('orders', 'delivery_lng')
    op.drop_column('orders', 'delivery_lat')
    # ### end Alembic commands ###
