"""empty message

Revision ID: c59ca423e400
Revises: 508f659b41ad
Create Date: 2019-10-05 21:31:34.469764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c59ca423e400'
down_revision = '508f659b41ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('duration', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'duration')
    # ### end Alembic commands ###
