"""empty message

Revision ID: fdfeaa5cf96d
Revises: c59ca423e400
Create Date: 2019-10-06 19:49:52.084064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfeaa5cf96d'
down_revision = 'c59ca423e400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'users', ['rider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'rider_id')
    # ### end Alembic commands ###
